CI: on Windows, use taskkill instead of pkill to abort Godot

diff --git a/.github/composite/godot-itest/action.yml b/.github/composite/godot-itest/action.yml
--- a/.github/composite/godot-itest/action.yml
+++ b/.github/composite/godot-itest/action.yml
@@ -157,6 +157,7 @@ runs:
       # * tee:      still output logs while scanning for errors
       # * grep -q:  no output, use exit code 0 if found -> thus also &&
       # * pkill:    stop Godot execution (since it hangs in headless mode); simple 'head -1' did not work as expected
+      #             since it's not available on Windows, use taskkill in that case.
       # * exit:     the terminated process would return 143, but this is more explicit and future-proof
       #
       # --disallow-focus: fail if #[itest(focus)] is encountered, to prevent running only a few tests for full CI
@@ -166,10 +167,14 @@ runs:
         $GODOT4_BIN --headless -- --disallow-focus ${{ inputs.godot-args }} 2>&1 \
         | tee "${{ runner.temp }}/log.txt" \
         | tee >(grep -E "SCRIPT ERROR:|Can't open dynamic library" -q && {
-        	printf "\n::error::godot-itest: unrecoverable Godot error, abort...\n";
-        	pkill godot
-            echo "OUTCOME=godot-runtime" >> $GITHUB_ENV
-        	exit 2
+          printf "\n::error::godot-itest: unrecoverable Godot error, abort...\n";
+          if [[ "$RUNNER_OS" == "Windows" ]]; then
+            taskkill -f -im godot*
+          else
+            pkill godot
+          fi
+          echo "OUTCOME=godot-runtime" >> $GITHUB_ENV
+          exit 2
         })
         
         echo "OUTCOME=success" >> $GITHUB_ENV
@@ -198,14 +203,14 @@ runs:
           "godot-runtime")
             echo "### :x: Godot runtime error" > $GITHUB_STEP_SUMMARY
             echo "$GODOT_BUILT_FROM" >> $GITHUB_STEP_SUMMARY
-        	echo "Aborted due to an error during Godot execution." >> $GITHUB_STEP_SUMMARY
+            echo "Aborted due to an error during Godot execution." >> $GITHUB_STEP_SUMMARY
             exit 2
             ;;
         
           "godot-leak")
             echo "### :x: Memory leak" > $GITHUB_STEP_SUMMARY
             echo "$GODOT_BUILT_FROM" >> $GITHUB_STEP_SUMMARY
-        	echo "Integration tests cause memory leaks." >> $GITHUB_STEP_SUMMARY
+            echo "Integration tests cause memory leaks." >> $GITHUB_STEP_SUMMARY
             exit 3
             ;;
         
