Fix 'ci-status' job not failing on cancellation
Use a bash script instead of underdocumented GitHub action glob magic syntax.

diff --git a/.github/workflows/full-ci.yml b/.github/workflows/full-ci.yml
--- a/.github/workflows/full-ci.yml
+++ b/.github/workflows/full-ci.yml
@@ -456,10 +456,23 @@ jobs:
 
     runs-on: ubuntu-20.04
     steps:
-      - name: "Success"
-        if: ${{ !(contains(needs.*.result, 'failure')) }}
-        run: exit 0
-
-      - name: "Failure"
-        if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
+      # Deliberate choice to use bash script and not GitHub Action glob syntax, as that is not well-documented and hard to get right.
+      # For example: contains(needs.*.result, 'success') does NOT work because * is a logical OR, thus true if a single job succeeds.
+      - name: "Determine success or failure"
+        run: |
+          DEPENDENCIES='${{ toJson(needs) }}'
+          
+          echo "Dependency jobs:"
+          all_success=true
+          for job in $(echo "$DEPENDENCIES" | jq -r 'keys[]'); do
+              status=$(echo "$DEPENDENCIES" | jq -r ".[\"$job\"].result")
+              echo "* $job -> $status"
+              if [[ "$status" != "success" ]]; then
+                  all_success=false
+              fi
+          done
+          
+          if [[ "$all_success" == "false" ]]; then
+              echo "One or more dependency jobs failed or were cancelled."
+              exit 1
+          fi
diff --git a/.github/workflows/minimal-ci.yml b/.github/workflows/minimal-ci.yml
--- a/.github/workflows/minimal-ci.yml
+++ b/.github/workflows/minimal-ci.yml
@@ -267,10 +267,21 @@ jobs:
 
     runs-on: ubuntu-20.04
     steps:
-      - name: "Success"
-        if: ${{ !(contains(needs.*.result, 'failure')) }}
-        run: exit 0
-
-      - name: "Failure"
-        if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
+      - name: "Determine success or failure"
+        run: |
+          DEPENDENCIES='${{ toJson(needs) }}'
+          
+          echo "Dependency jobs:"
+          all_success=true
+          for job in $(echo "$DEPENDENCIES" | jq -r 'keys[]'); do
+              status=$(echo "$DEPENDENCIES" | jq -r ".[\"$job\"].result")
+              echo "* $job -> $status"
+              if [[ "$status" != "success" ]]; then
+                  all_success=false
+              fi
+          done
+          
+          if [[ "$all_success" == "false" ]]; then
+              echo "One or more dependency jobs failed or were cancelled."
+              exit 1
+          fi
